# permissions for end users to view mykinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mykind-viewer-role
rules:
- apiGroups:
  - mygroup.ips.com.cn
  resources:
  - mykinds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mygroup.ips.com.cn
  resources:
  - mykinds/status
  verbs:
  - get
